// Auto-generated by G-DSP Golden Model
// RRC α=0.25, 5 taps, SPS=4
// Format: Q1.11 (12-bit signed), 5 coefficients
// DO NOT EDIT -- regenerate with scripts/golden_model.py

localparam integer NUM_RRC_COEFFS = 5;

function signed [11:0] rrc_coeff;
    input integer idx;
    case (idx)
         0: rrc_coeff = 12'sh218;  //   +536  (+0.261719)
         1: rrc_coeff = 12'sh32E;  //   +814  (+0.397461)
         2: rrc_coeff = 12'sh39A;  //   +922  (+0.450195)
         3: rrc_coeff = 12'sh32E;  //   +814  (+0.397461)
         4: rrc_coeff = 12'sh218;  //   +536  (+0.261719)
        default: rrc_coeff = 12'sh000;
    endcase
endfunction
