// Auto-generated by G-DSP Golden Model
// RRC α=0.25, 33 taps, SPS=4
// Format: Q1.11 (12-bit signed), 33 coefficients
// DO NOT EDIT -- regenerate with scripts/golden_model.py

localparam integer NUM_RRC_COEFFS = 33;

// iverilog-compatible: function instead of unpacked-array localparam
function automatic signed [11:0] rrc_coeff(input integer idx);
    case (idx)
         0: rrc_coeff = 12'sh012;  //    +18  (+0.008789)
         1: rrc_coeff = 12'sh009;  //     +9  (+0.004395)
         2: rrc_coeff = 12'shFF0;  //    -16  (-0.007812)
         3: rrc_coeff = 12'shFDB;  //    -37  (-0.018066)
         4: rrc_coeff = 12'shFE0;  //    -32  (-0.015625)
         5: rrc_coeff = 12'sh005;  //     +5  (+0.002441)
         6: rrc_coeff = 12'sh038;  //    +56  (+0.027344)
         7: rrc_coeff = 12'sh051;  //    +81  (+0.039551)
         8: rrc_coeff = 12'sh02E;  //    +46  (+0.022461)
         9: rrc_coeff = 12'shFD1;  //    -47  (-0.022949)
        10: rrc_coeff = 12'shF6D;  //   -147  (-0.071777)
        11: rrc_coeff = 12'shF55;  //   -171  (-0.083496)
        12: rrc_coeff = 12'shFC9;  //    -55  (-0.026855)
        13: rrc_coeff = 12'sh0CD;  //   +205  (+0.100098)
        14: rrc_coeff = 12'sh218;  //   +536  (+0.261719)
        15: rrc_coeff = 12'sh32E;  //   +814  (+0.397461)
        16: rrc_coeff = 12'sh39A;  //   +922  (+0.450195)
        17: rrc_coeff = 12'sh32E;  //   +814  (+0.397461)
        18: rrc_coeff = 12'sh218;  //   +536  (+0.261719)
        19: rrc_coeff = 12'sh0CD;  //   +205  (+0.100098)
        20: rrc_coeff = 12'shFC9;  //    -55  (-0.026855)
        21: rrc_coeff = 12'shF55;  //   -171  (-0.083496)
        22: rrc_coeff = 12'shF6D;  //   -147  (-0.071777)
        23: rrc_coeff = 12'shFD1;  //    -47  (-0.022949)
        24: rrc_coeff = 12'sh02E;  //    +46  (+0.022461)
        25: rrc_coeff = 12'sh051;  //    +81  (+0.039551)
        26: rrc_coeff = 12'sh038;  //    +56  (+0.027344)
        27: rrc_coeff = 12'sh005;  //     +5  (+0.002441)
        28: rrc_coeff = 12'shFE0;  //    -32  (-0.015625)
        29: rrc_coeff = 12'shFDB;  //    -37  (-0.018066)
        30: rrc_coeff = 12'shFF0;  //    -16  (-0.007812)
        31: rrc_coeff = 12'sh009;  //     +9  (+0.004395)
        32: rrc_coeff = 12'sh012;  //    +18  (+0.008789)
        default: rrc_coeff = 12'sh000;
    endcase
endfunction
