"""Generate RRC coefficients for 9 taps"""

import numpy as np

# Parameters
num_taps = 9
sps = 4
rolloff = 0.35
frac_bits = 11

# Generate RRC coefficients
t = np.arange(num_taps) - (num_taps - 1) / 2
t_norm = t / sps

coeffs = []
for i, tn in enumerate(t_norm):
    if tn == 0:
        h = 1 - rolloff + 4 * rolloff / np.pi
    elif abs(tn) == 1 / (4 * rolloff):
        h = (rolloff / np.sqrt(2)) * (
            (1 + 2 / np.pi) * np.sin(np.pi / (4 * rolloff))
            + (1 - 2 / np.pi) * np.cos(np.pi / (4 * rolloff))
        )
    else:
        num = np.sin(np.pi * tn * (1 - rolloff)) + 4 * rolloff * tn * np.cos(
            np.pi * tn * (1 + rolloff)
        )
        den = np.pi * tn * (1 - (4 * rolloff * tn) ** 2)
        h = num / den if den != 0 else 0
    coeffs.append(h)

# Normalize
coeffs = np.array(coeffs)
coeffs = coeffs / np.max(np.abs(coeffs))

# Convert to Q1.11 fixed-point
scale = 2**frac_bits - 1
coeffs_fixed = np.round(coeffs * scale).astype(int)

# Clamp to 12-bit signed range
coeffs_fixed = np.clip(coeffs_fixed, -2048, 2047)

# Output Verilog
print("// RRC Filter Coefficients (9 taps, SPS=4, rolloff=0.35)")
print("// Format: Q1.11 (12-bit signed)")
print("// Generated by gen_rrc_9taps.py")
print("")
print("function automatic signed [11:0] rrc_coeff(input int idx);")
print("    case (idx)")
for i, c in enumerate(coeffs_fixed):
    print(f"        {i}: rrc_coeff = 12'sd{c};")
print("        default: rrc_coeff = 12'sd0;")
print("    endcase")
print("endfunction")
